In [1]:
import numpy as np

X = np.random.rand(2)
W = np.random.rand(2,3)
B = np.random.rand(3)

print(X)
print(W)
print(B)

[0.72663129 0.22738967]
[[0.40120246 0.64374413 0.53814198]
 [0.30644899 0.21060626 0.76732509]]
[0.08302715 0.45728051 0.67688172]


In [3]:
X.shape
W.shape
B.shape

(3,)

In [4]:
Y = np.dot(X, W) + B

전치행렬

